---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: "Install/Uninstall tree"
    apt:
     name: tree
     state: present

- hosts: localGrp
  become: yes
  tasks:
  - name: "Remove Tree"
    apt:
      name: tree
      state: absent

- hosts: ExGrp
  become: yes
  tasks:
  - name: "Install git"
    apt:
      name: git
      state: present