---
- hosts: all
  become: yes
  tasks:
   - name: "update packages"
     apt:
       update_cache: yes
#NodeJS specific settings
#Installed from details in:
#https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04         
- hosts: app
  become: yes
  vars:
     folderpath: /home/ansible/nodesetup
  tasks:
   - name: "Creating Nodesetup Directory"
     file:
      path: "{{ folderpath }}"
      state: directory
      mode: 0755
   - name: "Download node js package setup to Directory"
     command: "curl -sL https://deb.nodesource.com/setup_8.x -o {{ folderpath}}/ nodesource_setup.sh"
   - name: "Execute downloaded shell script" 
     command: "sudo bash {{ folderpath}}/ nodesource_setup.sh"
   - name: "Install node js"
     command: "sudo apt-get install nodejs"  
